name: Python Selenium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    env:
      SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Replace with the specific version you need, e.g., '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest selenium

    - name: Run tests
      run: |
        ls
        pytest test_suits/test_login_page/test_login_func.py

